// svelte/src/routes/profile/+page.svelte
<section>
  <h2>Your Profile 👤</h2>

  <div class="profile-card">
    <p><strong>Name:</strong> Jane Doe</p>
    <p><strong>Role:</strong> Frontend Developer in training</p>
    <p><strong>Goals:</strong></p>
    <ul>
      <li>Master Svelte, React, and TypeScript</li>
      <li>Build full-stack apps with Node.js</li>
      <li>Learn DevOps basics (Docker, CI/CD, Kubernetes)</li>
    </ul>
  </div>
</section>

<style>
  .profile-card {
    background: #ffffff;
    padding: 1rem 1.25rem;
    border-radius: 0.75rem;
    box-shadow: 0 1px 4px rgba(15, 23, 42, 0.1);
    margin-top: 0.75rem;
  }

  ul {
    padding-left: 1.25rem;
  }
</style>

// vue/src/pages/Profile.vue
<template>
  <section>
    <h2>Your Profile 👤</h2>

    <div class="profile-card">
      <p><strong>Name:</strong> Jane Doe</p>
      <p><strong>Role:</strong> Frontend Developer in training</p>

      <h3>Goals:</h3>
      <ul>
        <li>Master Vue and TypeScript</li>
        <li>Build full-stack apps with Node.js</li>
        <li>Learn DevOps tools (Docker, CI/CD, Kubernetes)</li>
      </ul>
    </div>
  </section>
</template>

<style scoped>
.profile-card {
  background: #fff;
  padding: 1rem;
  border-radius: 12px;
  box-shadow: 0 2px 8px rgba(0,0,0,0.1);
}
</style>
